import { Lemon } from 'next/font/google'
import './globals.css'

const roboto = Lemon({ subsets: ['latin'], weight: ['400'] })

export const metadata = {
  title: 'SpiceDelish',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="max-w-7xl mx-auto p-10">
          {children}
        </main>
      </body>
    </html>
  )
}
